swagger: '2.0'
info:
  title: IBM Business Automation Workflow Process REST Interface
  version: 8.5.7.201703
  description: 'IBM Business Automation Workflow REST resources representing definitions and instances of processes, user tasks, and related objects.'
host: 'centosbaw151:9444'
basePath: /rest/bpm
consumes:
  - application/json
produces:
  - application/json
schemes:
  - https
securityDefinitions:
  basic_auth:
    type: basic
security:
  - basic_auth: []
paths:
  '/wle/v1/user/{user_id}':
    get:
      summary: Retrieve details about the user.
      description: Retrieve details about the user.
      operationId: User Details
      tags:
         - Organization API
      produces:
        - application/json
      parameters:
        - name: user_id
          in: path
          description: user id
          required: true
          type: string
        - name: includeInternalMemberships
          in: query
          description: 'Include Service Subtypes - A comma-separated list of one or more service subtypes to be included in the result set. If service subtypes are not specified, all service subtypes are included.'
          required: false
          type: boolean
        - name: refreshUser
          in: query
          description: Include Service Subtypes - Comma-separated list of types or service subtypes that should be excluded from referenced toolkits.
          required: false
          type: boolean
          default: false
        - name: includeEditableUserPreferences
          in: query
          description: Include Service Subtypes - Comma-separated list of types or service subtypes that should be excluded from referenced toolkits.
          required: false
          type: boolean
        - name: parts
          in: query
          description: Include Service Subtypes - Comma-separated list of types or service subtypes that should be excluded from referenced toolkits.
          required: false
          type: string
          enum: [none,all]
          default: none
      responses:
        '200':
          description: Items were successfully retrieved.
          schema:
            $ref: '#/definitions/UserDetails'
        '400':
          description: 'The request contains invalid parameters, or they are missing.'
          schema:
            $ref: '#/definitions/exception'
        '403':
          description: The caller is not authorized to perform the request.
          schema:
            $ref: '#/definitions/exception'
        '404':
          description: The requested resource does not exist.
          schema:
            $ref: '#/definitions/exception'
        '500':
          description: Internal server error.
          schema:
            $ref: '#/definitions/exception'
  /wle/v1/globalTeams:
    get:
      summary: Retrieves list of Teams
      description: Retrieves a list of Teams
      operationId: retrieveGlobalTeams
      tags:
        - Organization API
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: filter
          in: query
          description: Search by Team name starts with. example input is BPM*
          required: true
          type: string
      responses:
        '200':
          description: Team List data was successfully retrieved.
          schema:
            $ref: '#/definitions/RetrieveGlobalTeams'
        '400':
          description: 'The request contains invalid parameters, or they are missing.'
          schema:
            $ref: '#/definitions/exception'
        '403':
          description: The caller is not authorized to perform the request.
          schema:
            $ref: '#/definitions/exception'
        '404':
          description: The requested resource does not exist.
          schema:
            $ref: '#/definitions/exception'
        '500':
          description: Internal server error.
          schema:
            $ref: '#/definitions/exception'
definitions:
  data_object:
    description: Data object
    required:
      - name
      - data
    properties:
      name:
        type: string
        description: 'The name of the data input object, data output object, or variable.'
      data:
        type: object
        description: The value of the data object. This can be a simple type or a value that is described by a user-defined type.
  output:
    description: List of data objects.
    properties:
      output:
        type: array
        items:
          $ref: '#/definitions/data_object'
  input:
    description: List of data objects.
    type: object
    properties:
      input:
        type: array
        items:
          $ref: '#/definitions/data_object'
  exception:
    title: Exception
    description: Exception object describing REST API error details.
    required:
      - error_number
      - error_message
    properties:
      error_number:
        type: string
        description: Message ID of the exception.
      error_message:
        type: string
        description: Message text of the exception.
      error_message_parameters:
        type: array
        items:
          type: string
          description: An array of parameter strings that were inserted into the error message.
        description: Message text parameters of the exception.
  EmptyPayload:
    type: object
    properties:
      EmptyResponse:
        type: string
  ExposedItemListResult:
    description: List of exposed items
    properties:
      status:
        type: string
      data:
        type: object
        properties:
          exposedItemsList:
            type: array
            items:
              $ref: '#/definitions/ExposedItem'
  ExposedItem:
    description: Exposed Item Object
    properties:
      type:
        type: string
      subtype:
        type: string
      runURL:
        type: string
      itemID:
        type: string
      itemReference:
        type: string
      processAppID:
        type: string
      processAppName:
        type: string
      processAppAcronym:
        type: string
      snapshotID:
        type: string
      snapshotName:
        type: string
      snapshotCreatedOn:
        type: string
      display:
        type: string
      tip:
        type: boolean
      branchID:
        type: string
      branchName:
        type: string
      startURL:
        type: string
      isDefault:
        type: boolean
      isMobileReady:
        type: boolean
      ID:
        type: string
  UserDetails:
    description: UserDetails
    properties:
      status:
       type: string
      data: 
        type: object
        properties:
          userID: 
            type: integer
            format: int32
          userName: 
            type: string
          fullName: 
            type: string
          isDisabled: 
            type: boolean
          primaryGroup: 
            type: string
            format: nullable
          emailAddress: 
            type: string
            format: nullable
          editableUserPreferences:
                type: array
                items: 
                 type: string
          tasksCollaboration:
                type: string
                format: nullable
          memberships:
                type: array
                items:
                  type: string
  RetrieveGlobalTeamListItem:
    description: Retrieves list of Teams
    properties:
      teamId:
        type: string
      teamName:
        type: string
      processAppName:
        type: string
  RetrieveGlobalTeamList:
    description: Retrieve Business Data Search Result
    properties:
      teams:
        type: array
        items:
          $ref: '#/definitions/RetrieveGlobalTeamListItem'
  RetrieveGlobalTeams:
    description: Retrieve Business Data Fields
    properties:
      status:
        type: string
      data:
        $ref: '#/definitions/RetrieveGlobalTeamList'